"""
Category 14: Abstract Algebra - Group Orders

Generates modular rings Z_n* and computes subgroup orders.
Difficulty scales from undergraduate (prime n < 20) to frontier (composite n > 1000).
"""

import sympy
from sympy import isprime, factorint, totient

from ..core.generator import ForgeCategory, Problem


class AlgebraGroupsCategory(ForgeCategory):
    
    @property
    def name(self) -> str:
        return "algebra_groups"
    
    @property
    def display_name(self) -> str:
        return "Abstract Algebra: Group Orders"
    
    def get_difficulty_params(self, difficulty: int) -> dict:
        params = {
            1: {"n_range": (3, 20), "prefer_prime": True},
            2: {"n_range": (20, 50), "prefer_prime": False},
            3: {"n_range": (50, 200), "prefer_prime": False},
            4: {"n_range": (200, 500), "prefer_prime": False},
            5: {"n_range": (500, 1000), "prefer_prime": False},
        }
        return params.get(difficulty, params[3])
    
    def _multiplicative_order(self, a: int, n: int) -> int:
        """Compute the multiplicative order of a modulo n."""
        if sympy.gcd(a, n) != 1:
            return 0  # Not in the group
        
        order = 1
        current = a % n
        while current != 1:
            current = (current * a) % n
            order += 1
            if order > n:  # Safety check
                return 0
        return order
    
    def generate(self, difficulty: int, iteration: int) -> Problem:
        rng = self.get_rng(difficulty, iteration)
        params = self.get_difficulty_params(difficulty)
        
        n_range = params["n_range"]
        
        # Generate n
        n = int(rng.integers(*n_range))
        if params["prefer_prime"] and rng.random() < 0.7:
            # Find nearest prime
            while not isprime(n):
                n += 1
        
        # Ensure n > 2
        n = max(3, n)
        
        # Find elements coprime to n (the group Z_n*)
        coprime_elements = [a for a in range(1, n) if sympy.gcd(a, n) == 1]
        
        if not coprime_elements:
            # Shouldn't happen for n >= 3, but handle edge case
            n = 5
            coprime_elements = [1, 2, 3, 4]
        
        # Select a generator element
        generator = int(rng.choice(coprime_elements))
        
        # Compute the order of the subgroup generated by this element
        order = self._multiplicative_order(generator, n)
        
        # Filter out trivial cases (order 1 or 2)
        while order <= 2:
            generator = (generator + 1) % n
            if generator == 0:
                generator = 1
            order = self._multiplicative_order(generator, n)
        
        question = (
            f"Consider the multiplicative group Z_{n}* = {{a ∈ Z_{n} : gcd(a, {n}) = 1}}.\n\n"
            f"Let g = {generator} be an element of Z_{n}*.\n\n"
            f"Find the order of the subgroup generated by g, i.e., the smallest "
            f"positive integer k such that g^k ≡ 1 (mod {n}).\n\n"
            f"Provide the exact integer order."
        )
        
        answer = order
        
        return Problem(
            question=question,
            answer=answer,
            category=self.name,
            difficulty=difficulty,
            iteration=iteration,
            seed=self.base_seed,
            metadata={
                "n": n,
                "generator": generator,
                "order": order,
                "group_size": len(coprime_elements),
            },
        )
    
    def grade(self, prediction: str, answer: int) -> bool:
        try:
            pred = prediction.strip().replace(',', '').replace(' ', '')
            return int(pred) == int(answer)
        except (ValueError, TypeError):
            return False
