"""
Category 23: Formal Grammars

Generates Context-Free Grammars and tests string membership.
Difficulty scales from undergraduate (2 rules) to frontier (10 rules, depth 8).
"""

import random
from typing import Optional

from ..core.generator import ForgeCategory, Problem


class FormalGrammarsCategory(ForgeCategory):
    
    @property
    def name(self) -> str:
        return "formal_grammars"
    
    @property
    def display_name(self) -> str:
        return "Formal Grammars"
    
    def get_difficulty_params(self, difficulty: int) -> dict:
        params = {
            1: {"n_rules": 2, "max_depth": 3, "n_terminals": 2, "n_nonterminals": 2},
            2: {"n_rules": 3, "max_depth": 4, "n_terminals": 2, "n_nonterminals": 3},
            3: {"n_rules": 5, "max_depth": 5, "n_terminals": 3, "n_nonterminals": 4},
            4: {"n_rules": 7, "max_depth": 6, "n_terminals": 3, "n_nonterminals": 5},
            5: {"n_rules": 10, "max_depth": 8, "n_terminals": 4, "n_nonterminals": 6},
        }
        return params.get(difficulty, params[3])
    
    def _generate_cfg(self, rng, n_rules, n_terminals, n_nonterminals):
        """Generate a random context-free grammar in Chomsky Normal Form."""
        terminals = [chr(97 + i) for i in range(n_terminals)]  # a, b, c, ...
        nonterminals = [chr(65 + i) for i in range(n_nonterminals)]  # A, B, C, ...
        start = nonterminals[0]
        
        rules = {}
        for nt in nonterminals:
            rules[nt] = []
        
        # Ensure each nonterminal has at least one production
        for nt in nonterminals:
            # Add terminal production
            terminal = terminals[int(rng.integers(0, n_terminals))]
            rules[nt].append(terminal)
            
            # Add nonterminal productions (for CNF: exactly two nonterminals)
            if rng.random() < 0.7:
                nt1 = nonterminals[int(rng.integers(0, n_nonterminals))]
                nt2 = nonterminals[int(rng.integers(0, n_nonterminals))]
                rules[nt].append(nt1 + nt2)
        
        # Add more rules to reach target count
        while sum(len(v) for v in rules.values()) < n_rules:
            nt = nonterminals[int(rng.integers(0, n_nonterminals))]
            if rng.random() < 0.5:
                terminal = terminals[int(rng.integers(0, n_terminals))]
                rules[nt].append(terminal)
            else:
                nt1 = nonterminals[int(rng.integers(0, n_nonterminals))]
                nt2 = nonterminals[int(rng.integers(0, n_nonterminals))]
                rules[nt].append(nt1 + nt2)
        
        return rules, start, terminals, nonterminals
    
    def _generate_string(self, rules, start, max_depth, rng):
        """Generate a string from the grammar using random derivation."""
        def derive(symbol, depth):
            if depth > max_depth:
                # Force terminal if depth exceeded
                if symbol in rules:
                    for prod in rules[symbol]:
                        if len(prod) == 1 and prod.islower():
                            return prod
                return ""
            
            if symbol.islower():
                return symbol
            
            if symbol not in rules:
                return ""
            
            # Choose random production
            production = rules[symbol][int(rng.integers(0, len(rules[symbol])))]
            
            result = ""
            for char in production:
                result += derive(char, depth + 1)
            
            return result
        
        return derive(start, 0)
    
    def _check_membership(self, string, rules, start, max_steps=1000):
        """Check if a string can be generated by the grammar using CYK-like parsing."""
        n = len(string)
        if n == 0:
            return start in rules and "" in rules[start]
        
        # CYK algorithm
        # table[i][j] = set of nonterminals that can derive string[i:i+j+1]
        table = [[set() for _ in range(n)] for _ in range(n)]
        
        # Initialize for length 1 substrings
        for i in range(n):
            for nt, productions in rules.items():
                if string[i] in productions:
                    table[i][0].add(nt)
        
        # Fill for longer substrings
        for length in range(2, n + 1):  # length of substring
            for i in range(n - length + 1):  # start index
                for k in range(1, length):  # split point
                    for nt, productions in rules.items():
                        for prod in productions:
                            if len(prod) == 2:
                                left, right = prod[0], prod[1]
                                if left in table[i][k - 1] and right in table[i + k][length - k - 1]:
                                    table[i][length - 1].add(nt)
        
        return start in table[0][n - 1]
    
    def generate(self, difficulty: int, iteration: int) -> Problem:
        rng = self.get_rng(difficulty, iteration)
        params = self.get_difficulty_params(difficulty)
        
        # Generate grammar
        rules, start, terminals, nonterminals = self._generate_cfg(
            rng, params["n_rules"], params["n_terminals"], params["n_nonterminals"]
        )
        
        # Generate a string that IS in the language
        valid_string = self._generate_string(rules, start, params["max_depth"], rng)
        
        # Also generate a string that is NOT in the language
        invalid_string = ""
        for _ in range(50):
            test_len = rng.integers(1, len(valid_string) + 2)
            test_str = "".join(
                terminals[int(rng.integers(0, len(terminals)))]
                for _ in range(test_len)
            )
            if not self._check_membership(test_str, rules, start):
                invalid_string = test_str
                break
        
        # Format grammar
        grammar_str = f"Start symbol: {start}\nProductions:\n"
        for nt in nonterminals:
            if nt in rules:
                productions = " | ".join(rules[nt])
                grammar_str += f"  {nt} → {productions}\n"
        
        # Decide whether to ask about valid or invalid string
        ask_valid = rng.random() < 0.5
        
        if ask_valid and valid_string:
            test_string = valid_string
            answer = "Yes"
        elif invalid_string:
            test_string = invalid_string
            answer = "No"
        else:
            test_string = valid_string
            answer = "Yes"
        
        question = (
            f"Given the following Context-Free Grammar:\n\n"
            f"{grammar_str}\n"
            f"Does the grammar generate the string \"{test_string}\"?\n\n"
            f"Answer 'Yes' or 'No'."
        )
        
        return Problem(
            question=question,
            answer=answer,
            category=self.name,
            difficulty=difficulty,
            iteration=iteration,
            seed=self.base_seed,
            metadata={
                "rules": rules,
                "start": start,
                "test_string": test_string,
                "is_valid": answer == "Yes",
            },
        )
    
    def grade(self, prediction: str, answer: str) -> bool:
        try:
            pred = prediction.strip().lower()
            ans = answer.strip().lower()
            
            if ans == "yes":
                return "yes" in pred and "no" not in pred
            else:
                return "no" in pred and "yes" not in pred
        except:
            return False
